### PR TITLE
fix: Wrong bitness information

### LINKED ISSUE #6360: NodeJS LTS Linux download link dead
### URL:

https://nodejs.org/

### Browser Name:

Firefox

### Browser Version:

123.0

### Operating System:

Manjaro Linux 6.7.2

### How to reproduce the issue:

1. Using a Browser running under Linux, visit https://nodejs.org/en
2. under "Download Node.js", click the left hand button that says "20.11.1 LTS"

Expected: tar.xz download
Actual: Dead link, reporting a 404 nginx error

Additional info:
It seems the link points to a x86 build, which does not exist.
Specifically, it points to:  
 https://nodejs.org/dist/v20.11.1/node-v20.11.1-linux-x86.tar.xz
While it should point to:  
https://nodejs.org/dist/v20.11.1/node-v20.11.1-linux-x64.tar.xz

### PR DESCRIPTION
**Pull request by canerakdas**
## Description

If we cannot get the user's bitness information from the userAgent if `getHighEntropyValues` is not supported, the default is x86.

We act as if we are using the architecture, but since the x86 version is not officially distributed for Linux and Mac, users are directed to the wrong links.

This PR aims to create an alternative source to `getHighEntropyValues` by adding more to the conditions we check in `userAgent`.

Also, should we do something in the UI for versions that do not have an x86 version? (Maybe disabling the button?) cc @nodejs/nodejs-website 

## Validation

It would be better to test it on as many operating systems as possible in preview 👀 

## Related Issues

Fixes #6360

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
> Also, should we do something in the UI for versions that do not have an x86 version? (Maybe disabling the button?) cc @nodejs/nodejs-website

I thought we already disable x86 when x64 is not supported. But maybe it's because the initial state contains x86?

File: hooks/react-client/useDetectOS.ts [hunk 1]
```diff
@@ -31,7 +31,12 @@ const useDetectOS = () => {
           bitness:
             bitness === '64' ||
             userAgent?.includes('WOW64') ||
-            userAgent?.includes('Win64')
+            userAgent?.includes('Win64') ||
```
Comment (ovflowd) [inline hooks/react-client/useDetectOS.ts]: Could you make a simple regex with something like `/WOW64|Win64|x86_64|x86-64|x64;|AMD64/.test(userAgenmt)`?

Maybe worth also assigning this Regex into a dedicated const

**Review by manishprivet — APPROVED** [review]

**Review by mikeesto — APPROVED** [review]

**Review by AugustinMauroy — APPROVED** [review]

**Review by aymen94 — APPROVED** [review]

**Comment by canerakdas** [comment]
In this PR, we prevent x64 Linux users from trying to download the x86 version, but two more issues come to my mind cc @nodejs/nodejs-website 

1. What should we do if there is no official x86 support for a user with x86 architecture?
2. Arm or Apple silicon users who do not use the x64 platform and whose browser does not support `getHighEntropyValues`. There seems to be no problem since it is the only option on macOS. But I feel like we haven't been able to orient properly on Windows and Linux and need to do some development similar to what we did in this PR to figure out the architecture.

**Comment by canerakdas** [comment]
> I thought we already disable x86 when x64 is not supported. But maybe it's because the initial state contains x86?

I couldn't get the question 🙈

**Comment by ovflowd** [comment]
> > I thought we already disable x86 when x64 is not supported. But maybe it's because the initial state contains x86?
> 
> 
> 
> I couldn't get the question 🙈 

If the OS itself doesn't support x86 variants we should already disable prevent the state from reaching that. At least on the UI-side

The current bug is more related to the actual link generation

**Comment by ovflowd** [comment]
> Arm or Apple silicon users who do not use the x64 platform and whose browser does not support getHighEntropyValues. There seems to be no problem since it is the only option on macOS. But I feel like we haven't been able to orient properly on Windows and Linux and need to do some development similar to what we did in this PR to figure out the architecture.

There's no much we can do. There's so much we can do with automated OS detection. I hope eventually Firefox supports these APIs

**Review by shanpriyan — APPROVED** [review]

**Review by sxa — COMMENTED** [review]
I hit this today too. Is the `;` after `x64` intentional?

Other than that, I definitely approve of this being fixed - and it works for me (TM) - but i the `;` is an error then it should be fixed first.

**Comment by canerakdas** [comment]
> I hit this today too. Is the `;` after `x64` intentional?

This is a bit of an edge-case scenario, some examples contain `x64` in the user agent but whose architecture is not `x64`

For example, the user agent below;
`Links (0.99; Darwin 10.7.0 i386; 236x64)`

Architecture is `i386` but it contains `x64`

As far as I understand from looking at [this list](https://www.useragentstring.com/pages/All/), the `x64;` control is Firefox-based, but it is an added condition for what we cannot catch from other controls

**Comment by canerakdas** [comment]
> The current bug is more related to the actual link generation

There seemed to be no problem with the current version of link generation 🤔

To make the code more understandable for everyone, I added comments and updated the default values for OS that do not support `x86`
