### PR TITLE
fix: Added translation for snippet in package manager in download

### LINKED ISSUE #6849: Add translations of snippet comments from Download Package Manager boxes
The snippets below are defined on a TypeScript file and shown below:

image

We can call the translation service (t) and include translation strings within the i18n JSON files for such comments; otherwise, it feels like the translation is lacking here.

### LINKED ISSUE #6917: NPM should be lower case
### Enter your suggestions in details:

URL https://nodejs.org/en/download/package-manager

Multiple instructions include the line:

> verifies the right NPM version is in the environment

This is not aligned with npm's branding which states on https://github.com/npm/cli#faq-on-branding:

> #### Is it "npm" or "NPM" or "Npm"?

> **`npm`** should never be capitalized unless it is being displayed in a location that is customarily all-capitals (ex. titles on `man` pages).

This should be changed to:

> verifies the right npm version is in the environment

### PR DESCRIPTION
**Pull request by nilkhankari**
## Description

Added translation for snippet comments in package manager in download

## Related Issues

Fixes #6849
Fixes #6917
### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
(Question for website team) Wait our i18n engine didn't complete with English key if translated key isn't exist ?

image

File: apps/site/util/getNodeDownloadSnippet.ts [hunk 1]
```diff
@@ -16,94 +21,95 @@ export const getNodeDownloadSnippet = (release: NodeRelease, os: UserOS) => {
...
       docker pull node:${release.major}-${release.major >= 4 ? 'alpine' : 'slim'}
 
-      # verifies the right Node.js version is in the environment
-      docker run node:${release.major}-${release.major >= 4 ? 'alpine' : 'slim'} node -v # should print \`${release.versionWithPrefix}\`
+      # ${t('layouts.download.codeBox.verifiesRightNodejsVersion')}
+      docker run node:${release.major}-${release.major >= 4 ? 'alpine' : 'slim'} node -v # ${t('layouts.download.codeBox.shouldPrint', { version: release.versionWithPrefix })}
 
-      # verifies the right NPM version is in the environment
-      docker run node:${release.major}-${release.major >= 4 ? 'alpine' : 'slim'} npm -v # should print \`${release.npm}\``;
+      # ${t('layouts.download.codeBox.verifiesRoghtNpmVesrion')}
```
Comment (bmuenzenmeyer) [inline apps/site/util/getNodeDownloadSnippet.ts]:
```suggestion
      # ${t('layouts.download.codeBox.verifiesRightNpmVesrion')}
```

File: apps/site/i18n/locales/en.json [hunk 2]
```diff
@@ -292,7 +292,26 @@
       "codeBox": {
         "systemManagerWarning": "is not a Node.js package manager. Please ensure you already have {packageManager} installed.",
         "communityWarning": "Package managers and their installation scripts are not maintained by the Node.js project.",
-        "communityWarningReport": "If you encounter issues, please reach out to the package manager's maintainers."
+        "communityWarningReport": "If you encounter issues, please reach out to the package manager's maintainers.",
+        "installsNvm": "installs nvm (Node Version Manager)",
+        "downloadAndInstallNodejsRestartTerminal": "download and install Node.js (you may need to restart the terminal)",
+        "verifiesRightNodejsVersion": "verifies the right Node.js version is in the environment",
+        "verifiesRoghtNpmVesrion": "verifies the right NPM version is in the environment",
```
Comment (bmuenzenmeyer) [inline apps/site/i18n/locales/en.json]: as pointed out by https://github.com/nodejs/nodejs.org/issues/6917
```suggestion
        "verifiesRightNpmVesrion": "verifies the right npm version is in the environment",
```

File: apps/site/util/getNodeDownloadSnippet.ts [hunk 3]
```diff
@@ -16,94 +21,95 @@ export const getNodeDownloadSnippet = (release: NodeRelease, os: UserOS) => {
...
       choco install nodejs${release.isLts ? '-lts' : ''} --version="${release.version}"
 
-      # verifies the right Node.js version is in the environment
-      node -v # should print \`${release.major}\`
+      # ${t('layouts.download.codeBox.verifiesRightNodejsVersion')}
+      node -v # ${t('layouts.download.codeBox.shouldPrint', { version: release.major })}
 
-      # verifies the right NPM version is in the environment
-      npm -v # should print \`${release.npm}\``;
+      # ${t('layouts.download.codeBox.verifiesRoghtNpmVesrion')}
```
Comment (bmuenzenmeyer) [inline apps/site/util/getNodeDownloadSnippet.ts]:
```suggestion
      # ${t('layouts.download.codeBox.verifiesRightNpmVesrion')}
```

File: apps/site/util/getNodeDownloadSnippet.ts [hunk 4]
```diff
@@ -16,94 +21,95 @@ export const getNodeDownloadSnippet = (release: NodeRelease, os: UserOS) => {
...
       fnm use --install-if-missing ${release.major}
 
-      # verifies the right Node.js version is in the environment
-      node -v # should print \`${release.versionWithPrefix}\`
+      # ${t('layouts.download.codeBox.verifiesRightNodejsVersion')}
+      node -v # ${t('layouts.download.codeBox.shouldPrint', { version: release.versionWithPrefix })}
 
-      # verifies the right NPM version is in the environment
-      npm -v # should print \`${release.npm}\``;
+      # ${t('layouts.download.codeBox.verifiesRoghtNpmVesrion')}
```
Comment (bmuenzenmeyer) [inline apps/site/util/getNodeDownloadSnippet.ts]:
```suggestion
      # ${t('layouts.download.codeBox.verifiesRightNpmVesrion')}
```

File: apps/site/util/getNodeDownloadSnippet.ts [hunk 5]
```diff
@@ -16,94 +21,95 @@ export const getNodeDownloadSnippet = (release: NodeRelease, os: UserOS) => {
...
       brew install node@${release.major}
 
-      # verifies the right Node.js version is in the environment
-      node -v # should print \`${release.versionWithPrefix}\`
+      # ${t('layouts.download.codeBox.verifiesRightNodejsVersion')}
+      node -v # ${t('layouts.download.codeBox.shouldPrint', { version: release.versionWithPrefix })}
 
-      # verifies the right NPM version is in the environment
-      npm -v # should print \`${release.npm}\``;
+      # ${t('layouts.download.codeBox.verifiesRoghtNpmVesrion')}
```
Comment (bmuenzenmeyer) [inline apps/site/util/getNodeDownloadSnippet.ts]:
```suggestion
      # ${t('layouts.download.codeBox.verifiesRightNpmVesrion')}
```

File: apps/site/util/getNodeDownloadSnippet.ts [hunk 6]
```diff
@@ -16,94 +21,95 @@ export const getNodeDownloadSnippet = (release: NodeRelease, os: UserOS) => {
...
       nvm install ${release.major}
 
-      # verifies the right Node.js version is in the environment
-      node -v # should print \`${release.versionWithPrefix}\`
+      # ${t('layouts.download.codeBox.verifiesRightNodejsVersion')}
+      node -v # ${t('layouts.download.codeBox.shouldPrint', { version: release.versionWithPrefix })}
 
-      # verifies the right NPM version is in the environment
-      npm -v # should print \`${release.npm}\``;
+      # ${t('layouts.download.codeBox.verifiesRoghtNpmVesrion')}
```
Comment (bmuenzenmeyer) [inline apps/site/util/getNodeDownloadSnippet.ts]:
```suggestion
      # ${t('layouts.download.codeBox.verifiesRightNpmVesrion')}
```

File: apps/site/util/getNodeDownloadSnippet.ts [hunk 7]
```diff
@@ -16,94 +21,95 @@ export const getNodeDownloadSnippet = (release: NodeRelease, os: UserOS) => {
...
       fnm use --install-if-missing ${release.major}
 
-      # verifies the right Node.js version is in the environment
-      node -v # should print \`${release.versionWithPrefix}\`
+      # ${t('layouts.download.codeBox.verifiesRightNodejsVersion')}
+      node -v # ${t('layouts.download.codeBox.shouldPrint', { version: release.versionWithPrefix })}
 
-      # verifies the right NPM version is in the environment
-      npm -v # should print \`${release.npm}\``;
+      # ${t('layouts.download.codeBox.verifiesRoghtNpmVesrion')}
```
Comment (bmuenzenmeyer) [inline apps/site/util/getNodeDownloadSnippet.ts]:
```suggestion
      # ${t('layouts.download.codeBox.verifiesRightNpmVesrion')}
```

**Review by bmuenzenmeyer — DISMISSED** [review]
npm should be lowercased - and there is a misspelling of the word `Right` in the tests

File: apps/site/components/Downloads/Release/ReleaseCodeBox.tsx [hunk 8]
```diff
@@ -20,7 +20,7 @@ const ReleaseCodeBox: FC = () => {
   const t = useTranslations();
 
   useEffect(() => {
-    const updatedCode = getNodeDownloadSnippet(release, os)[platform];
+    const updatedCode = getNodeDownloadSnippet(release, os, t)[platform];
     // Docker and NVM support downloading tags/versions by their full release number
     // but usually we should recommend users to download "major" versions
     // since our Downlooad Buttons get the latest minor of a major, it does make sense
```
Comment (MikeMcC399) [inline apps/site/components/Downloads/Release/ReleaseCodeBox.tsx]:
```suggestion
    // since our Download Buttons get the latest minor of a major, it does make sense
```

**Review by MikeMcC399 — COMMENTED** [review]
My comments have been looked after. Thank you!

File: apps/site/util/getNodeDownloadSnippet.ts [hunk 9]
```diff
@@ -1,11 +1,16 @@
 import dedent from 'dedent';
+import type { TranslationValues } from 'next-intl';
 
 import type { NodeRelease } from '@/types';
 import type { PackageManager } from '@/types/release';
 import type { UserOS } from '@/types/userOS';
 
 // @TODO: These snippets should be extracted to i18n (?)
```
Comment (AugustinMauroy) [inline apps/site/util/getNodeDownloadSnippet.ts]:
```suggestion
```

**Review by AugustinMauroy — APPROVED** [review]
LGTM !

**Review by aymen94 — APPROVED** [review]
