### PR TITLE
fix: other downloads incorrect for 'current'

### LINKED ISSUE #5272: Current 'Other downloads' link on https://nodejs.org/en does not direct to /download/current
### URL:

https://nodejs.org/en

### Browser Name:

Chrome

### Browser Version:

Version 112.0.5615.49

### Operating System:

macOS Monterey, Version 12.6.5

### How to reproduce the issue:

1. Visit https://nodejs.org/en
2. Click 'Other downloads' under 'x.x.x Current' release.
3. Directs to https://nodejs.org/en/download, which defaults to LTS release downloads page view.
   * Instead, I'd expect the link to direct to straight to https://nodejs.org/en/download/current so the user doesn't have to manually have to switch to 'Current' from https://nodejs.org/en/download.
  
I guess something like `isLts ? '/download' : '/download/current'`  at [HomeDownloadButton.tsx#L38](https://github.com/nodejs/nodejs.org/blob/main/components/Home/HomeDownloadButton.tsx#L38) could be sufficient.

### PR DESCRIPTION
**Pull request by sxa**
Fixes https://github.com/nodejs/nodejs.org/issues/5272

I hit this bug when I was looking for the Windows/Arm64 builds on the web site - the link underneath the current release for "other downloads" takes you to the LTS ones without this.

### CODE REVIEW

File: components/Home/HomeDownloadButton.tsx [hunk 1]
```diff
@@ -15,8 +15,8 @@ const HomeDownloadButton = (props: HomeDownloadButtonProps) => {
   } = useNextraContext();
 
   const nodeDownloadLink = `https://nodejs.org/dist/${props.node}/`;
-  const nodeApiLink = `https://nodejs.org/dist/latest-${props.nodeMajor}/docs/api/`;
-
+  const nodeApiLink = `/latest-${props.nodeMajor}/docs/api/`;
```
Comment (ovflowd) [inline components/Home/HomeDownloadButton.tsx]: Are you sure this is correct?

File: components/Home/HomeDownloadButton.tsx [hunk 2]
```diff
@@ -15,8 +15,8 @@ const HomeDownloadButton = (props: HomeDownloadButtonProps) => {
...
+  const nodeAllDownloadsLink = `/download${props.isLts ? '/' : '/current'}`;
```
Comment (ovflowd) [inline components/Home/HomeDownloadButton.tsx:19]: Nice catch.

**Review by ovflowd — APPROVED** [review]
LGTM! But left a comment 🙃

File: components/Home/HomeDownloadButton.tsx (hunk 1 above)
Comment (sxa) [reply components/Home/HomeDownloadButton.tsx]: No I'm sure it's wrong :-)
I'll fix it. I didn't mean to edit that line. Thanks

**Review by richardlau — APPROVED** [review]

**Review by BethGriggs — APPROVED** [review]

File: components/Home/HomeDownloadButton.tsx (hunk 2 above)
Comment (sxa) [reply components/Home/HomeDownloadButton.tsx:19]: While it was updated and tested by me, credit to @BethGriggs too for spotting where the error was in the original issue :-)

**Review by ovflowd — APPROVED** [review]
LGTM! :shipit:

**Review by shanpriyan — APPROVED** [review]
LGTM !

**Comment by ovflowd** [comment]
Requesting fast-tracking here :)

**Review by UlisesGascon — APPROVED** [review]

**Review by manishprivet — APPROVED** [review]
