### PR TITLE
fix: added ellipsis for long content in breadcrumb

### LINKED ISSUE #6754: Enhancement: Breadcrumb breakpoint
## Issue
some of the  breadcrumb that are long have a inconsistent layout.
resulting in some layout shifting of the breadcrumb detail.
image
image

also in some case, the layout is breaking down like this below:
image
ref:
1. https://nodejs.org/en/learn/getting-started/nodejs-the-difference-between-development-and-production
## idea
Proposal: creating a breakpoint function of till 4 word (seems ideal when i tried) 
## Solution preview
- only trigger the breakpoint when the word count excede 4
image
image

### PR DESCRIPTION
**Pull request by TenzDelek**
## Description

added ellipsis for the long content in the breadcrumb to improve the layout shifting and in some case, breaking of the breadcrumb into next line.

## Validation
before:
image

after:
image

### Other Changes
- Layout is shifted toward the left.

## Related Issues
Fixes #6754 

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

File: components/Common/Breadcrumbs/index.tsx [hunk 1]
```diff
@@ -28,6 +29,13 @@ const Breadcrumbs: FC<BreadcrumbsProps> = ({
   const lengthOffset = maxLength - totalLength;
   const isOverflow = lengthOffset < 0;
 
+  const formatLabelWithWordCount = (label: string, maxWords: number) => {
```
Comment (ovflowd) [inline components/Common/Breadcrumbs/index.tsx]: JavaScript is not needed for this. We can achieve this with CSS ellipsis

https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

Comment (AugustinMauroy) [reply components/Common/Breadcrumbs/index.tsx]: `text-ellipsis` https://tailwindcss.com/docs/text-overflow

Comment (TenzDelek) [reply components/Common/Breadcrumbs/index.tsx]: will proceed with the change immediately

File: components/Common/Breadcrumbs/BreadcrumbLink/index.module.css [hunk 2]
```diff
@@ -1,4 +1,6 @@
 .link {
+  @apply w-full truncate;
```
Comment (ovflowd) [inline components/Common/Breadcrumbs/BreadcrumbLink/index.module.css]: We add one tailwind class per line. Check our docs ;d

File: components/Common/Breadcrumbs/index.tsx [hunk 3]
```diff
@@ -18,6 +18,7 @@ type BreadcrumbsProps = {
   maxLength?: number;
   hideHome?: boolean;
 };
+// Convert link.label to string and get its length
```
Comment (ovflowd) [inline components/Common/Breadcrumbs/index.tsx]: Is this comment needed?

Comment (TenzDelek) [reply components/Common/Breadcrumbs/index.tsx]: will remove that asap

File: components/Common/Breadcrumbs/BreadcrumbLink/index.module.css [hunk 4]
```diff
@@ -1,4 +1,7 @@
 .link {
+  @apply w-full 
+  truncate;
```
Comment (ovflowd) [inline components/Common/Breadcrumbs/BreadcrumbLink/index.module.css]:
```suggestion
    truncate;
```

I forgot to mention that we also add extra spaces for items from following lines (as you can see on the other lines hehe)

**Review by ovflowd — APPROVED** [review]
Alrighty, awesome contribution! Thanks for fixing this :)

File: components/Common/Breadcrumbs/BreadcrumbLink/index.module.css (hunk 4 above)
Comment (TenzDelek) [reply components/Common/Breadcrumbs/BreadcrumbLink/index.module.css]: haha will commit in a minute

Comment (ovflowd) [reply components/Common/Breadcrumbs/BreadcrumbLink/index.module.css]: I already did it 🫡

**Comment by ovflowd** [comment]
Can we update the code so that it attempts to use as much of the available width as possible?

image

As you can see on this screenshot, there's still available space 👀

**Comment by TenzDelek** [comment]
> Can we update the code so that it attempts to use as much of the available width as possible?
> 
> image
> As you can see on this screenshot, there's still available space 👀

hmm, seems interesting, in my viewport, the display is getting to it full. (maybe it depends on resolution of the screen)
image
what might be the appropriate length because for ellipsis to get trigger i believe we need a fix width (current implementation uses max-w-96 (384px)

**Comment by ovflowd** [comment]
> > Can we update the code so that it attempts to use as much of the available width as possible?
> 
> > 
> 
> > image
> 
> > As you can see on this screenshot, there's still available space 👀
> 
> 
> 
> hmm, seems interesting, in my viewport, the display is getting to it full. (maybe it depends on resolution of the screen)
> 
> image
> 
> what might be the appropriate length because for ellipsis to get trigger i believe we need a fix width (current implementation uses max-w-96 (384px)

max-w-full should work? Which sets the width to 100%; You dont need to define a static width for ellipsis to work.

**Comment by TenzDelek** [comment]
> > > Can we update the code so that it attempts to use as much of the available width as possible?
> > 
> > 
> > > 
> > 
> > 
> > > image
> > 
> > 
> > > As you can see on this screenshot, there's still available space 👀
> > 
> > 
> > hmm, seems interesting, in my viewport, the display is getting to it full. (maybe it depends on resolution of the screen)
> > image
> > what might be the appropriate length because for ellipsis to get trigger i believe we need a fix width (current implementation uses max-w-96 (384px)
> 
> max-w-full should work? Which sets the width to 100%; You dont need to define a static width for ellipsis to work.

the max-w-full doesn't seem to work. it is instead shifting the width further making the right panel smaller.
image
i believe from what i have seen, we are doing is making a fix length for a individual breaditem and applying the truncate to it. but what we oversight is that how we can make it truncate when it reaches the width like here the overall breadcrumb. (i hope this make sense haha)
i will again look into it and get back , thank you for pointing this out

**Comment by ovflowd** [comment]
> > > > Can we update the code so that it attempts to use as much of the available width as possible?
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > image
> > > 
> > > 
> > > > As you can see on this screenshot, there's still available space 👀
> > > 
> > > 
> > > hmm, seems interesting, in my viewport, the display is getting to it full. (maybe it depends on resolution of the screen)
> > > image
> > > what might be the appropriate length because for ellipsis to get trigger i believe we need a fix width (current implementation uses max-w-96 (384px)
> > 
> > 
> > max-w-full should work? Which sets the width to 100%; You dont need to define a static width for ellipsis to work.
> 
> the max-w-full doesn't seem to work. it is instead shifting the width further making the right panel smaller. image i believe from what i have seen, we are doing is making a fix length for a individual breaditem and applying the truncate to it. but what we oversight is that how we can make it truncate when it reaches the width like here the overall breadcrumb. (i hope this make sense haha) i will again look into it and get back , thank you for pointing this out

Im pretty sure what Im referring to is possible, you might just need to investigate a bit more xD

**Comment by TenzDelek** [comment]
hey @ovflowd 
Following up on our discussion about the breadcrumb layout, I've implemented the suggested changes. However, I've encountered an issue where extensive text in the breadcrumb section seems to be causing the right panel to shrink in width rather than truncating with an ellipsis (...).
I suspect this might be related to the current grid layout settings.  I have tried all the possibilities but was not able to come up with the solution haha, if possible can you give any possible solution that I might be oversighting  ;)

**Comment by ovflowd** [comment]
> hey @ovflowd Following up on our discussion about the breadcrumb layout, I've implemented the suggested changes. However, I've encountered an issue where extensive text in the breadcrumb section seems to be causing the right panel to shrink in width rather than truncating with an ellipsis (...). I suspect this might be related to the current grid layout settings. I have tried all the possibilities but was not able to come up with the solution haha, if possible can you give any possible solution that I might be oversighting ;)

Hi @TenzDelek, thanks for investigating! Unfortunately I don't have the time/capacity to look into this now, maybe someone from the Website team can? (cc @nodejs/nodejs-website)

**Comment by AugustinMauroy** [comment]
@TenzDelek now it's not centered anymore
Capture d’écran 2024-06-04 à 11 35 12

File: components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css [hunk 5]
```diff
@@ -1,5 +1,6 @@
 .list {
   @apply flex
-    items-center
-    gap-5;
+    w-full
+    gap-5
+    pl-2;
```
Comment (AugustinMauroy) [inline components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css]:
```suggestion
    px-2;
```
It's allow to have same padding left and right

Comment (TenzDelek) [reply components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css]: will implement that right off. also about the breadcrumb being on left, I believe that is due to making it full width. should we keep it or make it as default? the purpose of this was there was noticeable shifting of the breadcrumb when different text length occurs. so keeping it at a same starting point we can reduce that shifting.. :)

Comment (bmuenzenmeyer) [reply components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css]: I can see arguments either way, but since people are not really seeing the centered breadcrumb move (since it's at the bottom) it is a small concern to me. I'd rather it be centered, just as an opinion (and to preserve the original design's integrity), or if it is anchored to the left, it has padding similar to the content 

image

**Review by aymen94 — APPROVED** [review]

File: components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css (hunk 5 above)
Comment (TenzDelek) [reply components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css]: @bmuenzenmeyer  appreciate your input on this. I too see this issue in either way, but if it affecting the integrity of the original design, then definitely i will shift it back to the center as mention by both @AugustinMauroy and you:) .
 p.s I am still figuring out about our main conversation which is to make ellipsis on the longer text format. if any of the members have any navigation on that, it would be helpful :)

Comment (ovflowd) [reply components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css]: @bmuenzenmeyer can you follow up here? Are you fine with this getting merged as it is? :)

**Comment by bmuenzenmeyer** [comment]
This PR will need to be rebased or recreated now that https://github.com/nodejs/nodejs.org/pull/6850 merged.

File: components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css (hunk 5 above)
Comment (ovflowd) [reply components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css]: @bmuenzenmeyer still waiting for your follow-up here 😅

**Comment by ovflowd** [comment]
cc @TenzDelek could you please rebase your PR?

File: components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css (hunk 5 above)
Comment (bmuenzenmeyer) [reply components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css]: Fine with the left alignment.
I'd much prefer my left-padding / whitespace as I mocked up above.
Look how close the home icon is to the other scrollbar (perhaps Windows only) on the left.

image

**Comment by TenzDelek** [comment]
@ovflowd  @bmuenzenmeyer can you check once if the pr is valid. this is my first time doing a git rebase. if any issue with this pr ,will close this and raise a new one.

File: components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css (hunk 5 above)
Comment (TenzDelek) [reply components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css]: have changed the padding from 2 to 6.

**Review by bmuenzenmeyer — APPROVED** [review]
