### PR TITLE
fix: modified css module

### LINKED ISSUE #7569: Missing CSS style classes on about page left sidebar
### URL:

https://nodejs.org/en/about

### Browser Name:

FF

### Browser Version:

136.0.2

### Operating System:

windows 11 24H2

### How to reproduce the issue:

Sidebar on about page is rendered as shown below 

Image

> After investigating I found that sidebar `<li>` elements missing CSS style class. This bug is introduced in PR #7401

### PR DESCRIPTION
**Pull request by AugustinMauroy**
## Description

The css-module was modified I just copy the previous one. Also remove local in pathname to fix active link detection.

## Validation

Capture d’écran 2025-03-25 à 10 38 52

## Related Issues

Close #7569 

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

File: apps/site/components/withProgressionSidebar.tsx [hunk 1]
```diff
@@ -2,7 +2,11 @@
 
 import ProgressionSidebar from '@node-core/ui-components/Common/ProgressionSidebar';
 import { usePathname } from 'next/navigation';
-import { useTranslations, type RichTranslationValues } from 'next-intl';
+import {
```
Comment (ovflowd) [inline apps/site/components/withProgressionSidebar.tsx]: Can you separate type imports from regular imports?

**Review by ovflowd — APPROVED** [review]

**Comment by ovflowd** [comment]
Does this also fix the bug in the logo?

File: apps/site/components/withProgressionSidebar.tsx (hunk 1 above)
Comment (AugustinMauroy) [reply apps/site/components/withProgressionSidebar.tsx]: Yup good catch (VSC auto import)

**Comment by AugustinMauroy** [comment]
> Does this also fix the bug in the logo?

Nop I didn't get how to fix logo issue. Because dark still Is correctly applied on dark theme and correctly remove on light theme.

But it's didn't applied light style.

**Comment by ovflowd** [comment]
> > Does this also fix the bug in the logo?
> 
> Nop I didn't get how to fix logo issue. Because dark still Is correctly applied on dark theme and correctly remove on light theme.
> 
> But it's didn't applied light style.

I think we pass to the logo what theme we are at or something? @avivkeller if you can investigate as a follow-up 🙏

**Comment by AugustinMauroy** [comment]
> > > Does this also fix the bug in the logo?
> > 
> > 
> > Nop I didn't get how to fix logo issue. Because dark still Is correctly applied on dark theme and correctly remove on light theme.
> > But it's didn't applied light style.
> 
> I think we pass to the logo what theme we are at or something? @avivkeller if you can investigate as a follow-up 🙏

We define it by tailwind classes https://github.com/nodejs/nodejs.org/blob/435becbf26727c9034e22a96fe627a2e422085ec/packages/ui-components/Icons/Logos/Nodejs.tsx#L25

**Comment by AugustinMauroy** [comment]
I'm fast tracking because it's affect a lot user

**Comment by avivkeller** [comment]
> I think we pass to the logo what theme we are at or something? @avivkeller if you can investigate as a follow-up 🙏

Yep! I'll be on that ASAP.

**Comment by AugustinMauroy** [comment]
> Yep! I'll be on that ASAP.

Thanks 🫶🏻

**Comment by avivkeller** [comment]
Okay. I'm so sorry about the UI differences, I'm currently looking into it and will open a PR as soon I as complete my investigation.
