### PR TITLE
fix(ui): make LinkWithArrow behave like accessible button for modal open

### LINKED ISSUE #8048: Details Button not keyboard accessible
### URL:

https://nodejs.org/en/about/previous-releases

### Browser Name:

Chrome

### Browser Version:

138.0.7204.169 (Official Build) (64-bit)

### Operating System:

Windows 10

### How to reproduce the issue:

1. Navigate to https://nodejs.org/en/about/previous-releases
2. tab to table within https://nodejs.org/en/about/previous-releases#looking-for-the-latest-release-of-a-version-branch
3. cannot tab to any of the entries `Details`

Image

> discovered during #7990 testing, but happening in production now too

### PR DESCRIPTION
**Pull request by Mohit5Upadhyay**
## Description

This PR solve the issue: #8048 by improving accessibility using `LinkWithArrow` as a button to trigger the modal with correct `role`, `tabIndex`, `aria-label`, and keyboard support.

## Validation

https://github.com/user-attachments/assets/209d67a3-be24-4e3a-81f2-89b101e61130

## Related Issues

Closes #8048 

### Check List

- [✅] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [✅] I have run `pnpm format` to ensure the code follows the style guide.
- [✅] I have run `pnpm test` to check if all tests are passing.
- [✅] I have run `pnpm build` to check if the website builds without errors.
- [✅] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by avivkeller** [comment]
There should be a way to do this without adding the additional listener, right?

According to https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event, the "click" event is emitted on key press.

**Comment by Mohit5Upadhyay** [comment]
Thank you for the suggestion, @avivkeller! 🙌

> According to https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event, the "click" event is emitted on key press.

You're absolutely right — a manual listener isn’t needed if the element were a native `<button> or <a href>`.

Since `LinkWithArrow` renders a non-interactive element  under the hood (`<span>`) keyboard events like `Enter` and `Space` won't trigger the `on click` natively, even with `role="button" and tabIndex={0}`.

To solve this while preserving the current structure, I added a `onKeyDown` handler that listens for Enter and Space and invokes the modal.

Alternatively, I'm also exploring replacing the underlying element with a native `<button>` using `asChild` for improved semantics and cleaner handling if you suggest.

Really appreciate your input — Please, Let me know  🙏 
Thanks!

**Comment by avivkeller** [comment]
I'd rather convert it to an anchor or button, instead of adding redundant listeners

**Comment by MattIPv4** [comment]
+1 this should be an actual semantic button

**Comment by Mohit5Upadhyay** [comment]
Hi @avivkeller @MattIPv4 👋

I've updated the implementation to use a `semantic <button>` element instead of a non-interactive `LinkWithArrow` element for triggering the release details modal, as per your suggestion.

This change improves accessibility and removes the redundant event listener.

Let me know if anything else needs adjustment — happy to iterate!

**Comment by avivkeller** [comment]
What if we, instead, change the LinkWithArrow component itself to be an `a`, regardless of whether there is a link, meaning this change will work on all cases?

**Comment by Mohit5Upadhyay** [comment]
Thanks for the suggestion!, @avivkeller 🙌

> change the LinkWithArrow component itself to be an a, regardless of whether there is a link, meaning this change will work on all cases?

Changing `LinkWithArrow` to always render an `<a> tag` — even when there's no href — won't fully or properly address accessibility concerns.
- An `<a>` without an `href` is not `keyboard-focusable` by default 
- Requires manual handling of `tabIndex`, `role="button"`, and keyboard events to behave like a `button`

That’s why it’s more robust to use the appropriate semantic element (`<a> for links, <button> for actions`).
Let me know what you think!

**Comment by avivkeller** [comment]
Okay, so why don't we have it be a `button` where there isn't a link, and an `a` (anchor) otherwise? Regardless, this should be changed on the `LinkWithArrow` level

**Comment by Mohit5Upadhyay** [comment]
Hi @avivkeller 👋

I've updated the `LinkWithArrow` component as suggested:
- It now renders an `<a>` when `href` is provided
- Falls back to a `<button>` otherwise
- Handles both accessibility and semantics properly at the component level

Let me know if any further refinements are needed — happy to iterate! 🙌

File: apps/site/components/LinkWithArrow.tsx [hunk 1]
```diff
@@ -1,28 +1,45 @@
...
-const LinkWithArrow: FC<PropsWithChildren<LinkWithArrowProps>> = ({
-  children,
-  asChild = false,
-  ...props
-}) => {
-  const Comp = asChild ? Slot : Link;
+const LinkWithArrow: FC<PropsWithChildren<LinkWithArrowProps>> = props => {
+  const { children, className, ...rest } = props;
+
+  if ('href' in props && props.href) {
```
Comment (avivkeller) [inline apps/site/components/LinkWithArrow.tsx]:
```suggestion
  if (rest.href) {
```

File: apps/site/components/LinkWithArrow.tsx [hunk 2]
```diff
@@ -1,28 +1,45 @@
...
+      </Link>
+    );
+  }
 
   return (
-    <Comp {...props}>
+    <button
+      type="button"
+      {...(rest as ButtonHTMLAttributes<HTMLButtonElement>)}
+      className={`${className || ''} text-green-600 hover:text-green-900 dark:text-green-400 dark:hover:text-green-200`}
```
Comment (avivkeller) [inline apps/site/components/LinkWithArrow.tsx]: Use the `classNames` utility

File: apps/site/components/LinkWithArrow.tsx [hunk 3]
```diff
@@ -1,28 +1,45 @@
...
+  | (Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'type'> & { href?: never });
 
-const LinkWithArrow: FC<PropsWithChildren<LinkWithArrowProps>> = ({
-  children,
-  asChild = false,
-  ...props
-}) => {
-  const Comp = asChild ? Slot : Link;
+const LinkWithArrow: FC<PropsWithChildren<LinkWithArrowProps>> = props => {
+  const { children, className, ...rest } = props;
```
Comment (avivkeller) [inline apps/site/components/LinkWithArrow.tsx]:
```suggestion
const LinkWithArrow: FC<PropsWithChildren<LinkWithArrowProps>> = ({ children, className, ...rest }) => {
```

File: apps/site/components/LinkWithArrow.tsx [hunk 4]
```diff
@@ -1,28 +1,45 @@
...
-  | ({ asChild: true } & SlotProps);
+  | ({ href: string } & AnchorHTMLAttributes<HTMLAnchorElement>)
+  | (Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'type'> & { href?: never });
 
-const LinkWithArrow: FC<PropsWithChildren<LinkWithArrowProps>> = ({
-  children,
-  asChild = false,
-  ...props
-}) => {
-  const Comp = asChild ? Slot : Link;
```
Comment (avivkeller) [inline apps/site/components/LinkWithArrow.tsx:18]: Nice! Just wondering if we can remove @radix-ui's Slot as a dependency (is it used elsewhere?)

**Review by avivkeller — COMMENTED** [review]
Almost there!

File: apps/site/components/LinkWithArrow.tsx [hunk 5]
```diff
@@ -1,28 +1,45 @@
...
+  PropsWithChildren,
+} from 'react';
 
 import Link from '#site/components/Link';
 
 type LinkWithArrowProps =
-  | ({ asChild?: false } & ComponentProps<typeof Link>)
-  | ({ asChild: true } & SlotProps);
+  | ({ href: string } & AnchorHTMLAttributes<HTMLAnchorElement>)
+  | (Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'type'> & { href?: never });
```
Comment (avivkeller) [inline apps/site/components/LinkWithArrow.tsx]: Can we do a props of "Link" vs props of "HTMLButtonType"?

File: apps/site/components/LinkWithArrow.tsx (hunk 4 above)
Comment (Mohit5Upadhyay) [reply apps/site/components/LinkWithArrow.tsx:18]: I searched the project and confirmed that `@radix-ui/react-slot` is not used anywhere in the codebase. It was previously used  (with `asChild`), but our current implementation no longer relies on it.

Comment (Mohit5Upadhyay) [reply apps/site/components/LinkWithArrow.tsx:18]: Should i remove `@radix-ui/react-slot` from the dependencies to keep the project clean ?

**Comment by Mohit5Upadhyay** [comment]
Hi @avivkeller ,

> Can we do a props of "Link" vs props of "HTMLButtonType"?

Yes, this can be done like this
```
LinkWithArrowProps =
  | { kind: 'link'; props: AnchorHTMLAttributes<HTMLAnchorElement> }
  | { kind: 'button'; props: ButtonHTMLAttributes<HTMLButtonElement> };
```

but for that we have to refractor some files like `DownloadLink.tsx` , `DetailsButton.tsx` , `ChangelogLink.tsx` ,`ReleaseCodeBox.tsx` accordingly  

```
//previous
<LinkWithArrow href={downloadLink}>{children}</LinkWithArrow>;

//updated
<LinkWithArrow
      kind="link"
      props={{ href: downloadLink }}
    >
      {children}
    </LinkWithArrow>
```

**Comment by avivkeller** [comment]
That's not what I meant, I meant the type definition itself. If it's not possible, forget it

**Comment by Mohit5Upadhyay** [comment]
Hi @avivkeller 👋,

Thanks for the clarification!

I misunderstood your suggested approach.
> That's not what I meant, I meant the type definition itself. If it's not possible, forget it

Since you meant it’s fine to skip if not possible— I’ve kept the simpler & skip it.

All other previous changes are applied as ✅ suggested  above.

Let me know if anything else is needed!

**Comment by avivkeller** [comment]
@Mohit5Upadhyay May I push a commit to resolve some last minute things, then we are good to go?

**Review by avivkeller — APPROVED** [review]

**Comment by MattIPv4** [comment]
conflicts :P

**Comment by avivkeller** [comment]
@nodejs/web-infra PTAL, I may have broken something 😅

**Comment by MattIPv4** [comment]
`Error: Cannot apply utility class 'after:md:-left-1/2' because the 'md' variant does not exist.` + `Module not found: Can't resolve './components/common/LinkWithArrow'`

**Comment by avivkeller** [comment]
> `Error: Cannot apply utility class 'after:md:-left-1/2' because the 'md' variant does not exist.` + `Module not found: Can't resolve './components/common/LinkWithArrow'`

I'll fix them today or tomorrow., thank you

**Review by ovflowd — APPROVED** [review]

**Comment by ovflowd** [comment]
@avivkeller / @Mohit5Upadhyay there's a conflict, can any of you resolve it?

**Comment by Mohit5Upadhyay** [comment]
Apologies, I think I may have broken something 😅.

**Review by AugustinMauroy — APPROVED** [review]

**Comment by avivkeller** [comment]
> Apologies, I think I may have broken something 😅.

No worries! I can resolve the conflicts later today

**Comment by Mohit5Upadhyay** [comment]
> No worries! I can resolve the conflicts later today

Thanks @avivkeller for taking care of this 🙏. I apologize — I tried resolving the conflicts earlier but ended up breaking something and it got a bit messed up. 
I’ll make sure to be more careful with conflict resolution next time.
Really appreciate your help in fixing it!

**Comment by avivkeller** [comment]
Ack! I got swamped, ping me again if you need help, I'll be available.
