### PR TITLE
Fix breadcrumbs not updating

### LINKED ISSUE #6365: Breadcrumbs not updating on Learn pages
### URL:

https://nodejs-bjq0pcoku-openjs.vercel.app/en/learn/getting-started/how-to-install-nodejs

### Browser Name:

Chrome

### Browser Version:

122.0.6261.69

### Operating System:

MacOS

### How to reproduce the issue:

The breadcrumbs on the Learn pages display "Diagnostics" regardless of what module the page actually falls under. The breadcrumbs should dynamically update to reflect the correct module.
Screen Shot 2024-02-29 at 1 19 49 pm

### PR DESCRIPTION
**Pull request by yanggggjie**
## Description

fix: https://github.com/nodejs/nodejs.org/issues/6365

### before
image

### after
image

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

File: components/withBreadcrumbs.tsx [hunk 1]
```diff
@@ -20,11 +21,55 @@ const WithBreadcrumbs: FC = () => {
...
-      .flat()
-      .filter(([, item]) => pathname.includes(item.link))
-      .map(([, item]) => ({ label: item.label, href: item.link }));
+    const navigationTree: Array<[string, MappedNavigationEntry]> =
+      getSideNavigation([navigationKey as NavigationKeys]);
+
+    const toCamelCase = (str: string) => {
+      return str
+        .split('-')
+        .map((word, index) =>
```
Comment (ovflowd) [inline components/withBreadcrumbs.tsx]: I assume you're capitalising the string here. You don't need to do this with JavaScript. CSS can do that. Also we do have an utility for camel case already in the code I assume, (check util folder)

File: components/withBreadcrumbs.tsx [hunk 2]
```diff
@@ -20,11 +21,55 @@ const WithBreadcrumbs: FC = () => {
...
+          index === 0 ? word : word[0].toUpperCase() + word.slice(1)
+        )
+        .join('');
+    };
+
+    const pathList = pathname
+      .split('/')
+      .filter(item => {
```
Comment (ovflowd) [inline components/withBreadcrumbs.tsx]: No need of brackets here

File: components/withBreadcrumbs.tsx [hunk 3]
```diff
@@ -20,11 +21,55 @@ const WithBreadcrumbs: FC = () => {
...
+        return item !== '';
+      })
+      .map(path => {
```
Comment (ovflowd) [inline components/withBreadcrumbs.tsx]: No need of brackets here

File: components/withBreadcrumbs.tsx [hunk 4]
```diff
@@ -20,11 +21,55 @@ const WithBreadcrumbs: FC = () => {
...
+        return toCamelCase(path);
+      });
+
+    const findPathInTree = (
```
Comment (ovflowd) [inline components/withBreadcrumbs.tsx]: This seems super confusing and the time complexity of this is also not great. I'm quite sure you can solve this issue by using `.flat()` (to flatten the tree, as we don't need to navigate on the actual tree) and use simple ES6 builtins.

@canerakdas if you have time can you give a look into this? The old code was working at some point so I assume the current issue must be something silly

File: components/withBreadcrumbs.tsx (hunk 1 above)
Comment (yanggggjie) [reply components/withBreadcrumbs.tsx]: There is no such fucniton util. Should I move it to util as a new file?

File: components/withBreadcrumbs.tsx [hunk 5]
```diff
@@ -20,11 +21,38 @@ const WithBreadcrumbs: FC = () => {
...
+      .filter(item => item !== '')
+      .map(toCamelCase);
+
+    return pathList.reduce(
+      (acc, path) => {
+        const currentNode = acc.currentNode.find(([key]) => key === path);
+        if (currentNode) {
+          const [, { label, link = '', items = [] }] = currentNode;
+          if (label) {
+            acc.result.push({ label, href: link });
```
Comment (ovflowd) [inline components/withBreadcrumbs.tsx]: Instead of using `push` you can do `return acc.concat()`

File: components/withBreadcrumbs.tsx [hunk 6]
```diff
@@ -20,11 +21,38 @@ const WithBreadcrumbs: FC = () => {
...
     }
 
-    return getSideNavigation([navigationKey as NavigationKeys])
-      .map(([, item]) => item.items)
-      .flat()
-      .filter(([, item]) => pathname.includes(item.link))
-      .map(([, item]) => ({ label: item.label, href: item.link }));
+    const navigationTree = getSideNavigation([navigationKey as NavigationKeys]);
+
+    const toCamelCase = (str: string) =>
```
Comment (ovflowd) [inline components/withBreadcrumbs.tsx]: As mentioned before, please extract this to the `stringUtils` utility 👀 this shouldn't be here. You can also achieve the same with regex. Here's an optimised version that works for any sort of given string:

```ts
const toCamelCase = (str: string) =>
  str
    .replace(/[^a-zA-Z0-9]+(.)/g, (m, chr) => chr.toUpperCase())
    .replace(/^[A-Z]/, chr => chr.toLowerCase());
```

File: components/withBreadcrumbs.tsx [hunk 7]
```diff
@@ -20,11 +21,38 @@ const WithBreadcrumbs: FC = () => {
...
+          }
+          acc.currentNode = items;
+        }
+        return acc;
+      },
+      {
+        currentNode: navigationTree,
+        result: [] as Array<BreadcrumbLink>,
+      }
+    ).result;
```
Comment (ovflowd) [inline components/withBreadcrumbs.tsx]: If you only need the result array, then the reduce function should only have an array.

Instead of using this `currentNode` which is pretty much a pointer, you can make a local variable (outside of the reduce callback) called `let currentNode = navigationTree`

And simply keep updating it inside the reduce loop. This reduces the complexity of your reduce loop

File: components/withBreadcrumbs.tsx (hunk 1 above)
Comment (ovflowd) [reply components/withBreadcrumbs.tsx]: Yeah that's what Im saying, I even gave a snippet that should be better (more generic)

File: components/withBreadcrumbs.tsx [hunk 8]
```diff
@@ -2,29 +2,40 @@
...
-      .map(([, item]) => ({ label: item.label, href: item.link }));
+    const navigationTree = getSideNavigation([navigationKey as NavigationKeys]);
+    const pathList = pathname
+      .split('/')
+      .filter(item => item !== '')
+      .map(dashToCamelCase);
+
+    let currentNode = navigationTree;
+
+    return pathList.reduce((breadcrumbs, path) => {
```
Comment (ovflowd) [inline components/withBreadcrumbs.tsx:37]: As a last change, can you add some inline code docs explaining what this code is doing, just to make it easy for newcomers to see what it is doing.

**Review by ovflowd — APPROVED** [review]
LGTM! Thank you for your contribution, and for going over the feedback :)

File: components/withBreadcrumbs.tsx (hunk 8 above)
Comment (yanggggjie) [reply components/withBreadcrumbs.tsx:37]: okok, Thank you for your patient help!
