### PR TITLE
Fix slashes on Windows.

### LINKED ISSUE #2396: Wrong URLs on Windows
While playing with the source code on my Windows dev VM, I notice that there are hundreds of wrong URLs.

For example: `<a href="/en/blog/release\v10.16.2/">v10.16.2</a>`

It seems `post.path` wrongfully uses backslashes on Windows.

Not super important since most people don't use Windows, but I thought I'd report it in case someone has the time to help.

### PR DESCRIPTION
**Pull request by XhmikosR**
There's a bug somewhere which results in backslashes in paths when building on Windows.

Maybe the name should be normalize slashes or something? I just wanted to keep it short here.

Fixes #2396

### CODE REVIEW

**Comment by MylesBorins** [comment]
Is there anyone with a windows box who can verify?

**Comment by XhmikosR** [comment]
Here's the output without this patch (trimmed) to get an idea:

```
C:\Users\xmr\Desktop\nodejs.org>npm run test:html

> nodejs.org@ test:html C:\Users\xmr\Desktop\nodejs.org
> node scripts/vnu-jar.js

"file:/C:/Users/xmr/Desktop/nodejs.org/build/ar/docs/guides/abi-stability/index.html":32.3-32.80: error: Bad value "https://nodejs.org/ar/docs/guides\abi-stability/" for attribute "href" on element "link": Backslash ("\") used as path segment delimiter.
"file:/C:/Users/xmr/Desktop/nodejs.org/build/ar/docs/guides/anatomy-of-an-http-transaction/index.html":32.3-32.97: error: Bad value "https://nodejs.org/ar/docs/guides\anatomy-of-an-http-transaction/" for attribute "href" on element "link": Backslash ("\") used as path segment delimiter.
"file:/C:/Users/xmr/Desktop/nodejs.org/build/ar/docs/guides/debugging-getting-started/index.html":32.3-32.92: error: Bad value "https://nodejs.org/ar/docs/guides\debugging-getting-started/" for attribute "href" on element "link": Backslash ("\") used as path segment delimiter.
"file:/C:/Users/xmr/Desktop/nodejs.org/build/ar/docs/guides/getting-started-guide/index.html":32.3-32.88: error: Bad value "https://nodejs.org/ar/docs/guides\getting-started-guide/" for attribute "href" on element "link": Backslash ("\") used as path segment delimiter.
"file:/C:/Users/xmr/Desktop/nodejs.org/build/ar/docs/guides/index.html":32.3-32.66: error: Bad value "https://nodejs.org/ar/docs\guides/" for attribute "href" on element "link": Backslash ("\") used as path segment delimiter.
"file:/C:/Users/xmr/Desktop/nodejs.org/build/ar/docs/guides/publishing-napi-modules/index.html":32.3-32.90: error: Bad value "https://nodejs.org/ar/docs/guides\publishing-napi-modules/" for attribute "href" on element "link": Backslash ("\") used as path segment delimiter.
...
```

My main concern is that I don't know where this bug comes from. Is it from metalsmith itself?

File: scripts/helpers/slashes.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+'use strict'
+
+module.exports = function (str) {
+  return str.replace(/\\/g, '/')
```
Comment (XhmikosR) [inline scripts/helpers/slashes.js]: Should I wrap this in `process.platform === 'win32'`?

Or even use https://www.npmjs.com/package/slash?

Comment (ghost) [reply scripts/helpers/slashes.js]: I tend to add 'process.platform === 'win32', easy and quick.

**Comment by ghost** [comment]
@XhmikosR, Have you submitted `test:html` in the  package.json?
捕获

**Comment by XhmikosR** [comment]
@MaledongGit: what do you mean? If you mean the vnu addition, that's in #2469, which isn't ready yet.

**Comment by ghost** [comment]
@XhmikosR ：Well……I fetched the latest version of codes and I cannot use `test:html`, I want to know whether this is already added in the package.json or not. Otherwises I'll merge it into the repository ;)

**Comment by XhmikosR** [comment]
If you mean the slashes PR, that's ready. The vnu PR is not ready,I list
the TODO there.

File: scripts/helpers/slashes.js [hunk 2]
```diff
@@ -0,0 +1,5 @@
+'use strict'
+
+module.exports = function (str) {
+  return process.platform === 'win32' && str.replace(/\\/g, '/')
```
Comment (XhmikosR) [inline scripts/helpers/slashes.js:4]: The process.platform check seems inconsistent now since in summary.js I don't do the same.
