### PR TITLE
fix: check latest release LTS status for version support

### LINKED ISSUE #8786: `/download/current` broken
### URL:

https://nodejs.org/en/download/current

### Browser Name:

All

### Browser Version:

All

### Operating System:

All

### How to reproduce the issue:

Access https://nodejs.org/en/download/current, or observe the footer on any page as that is also missing the current release badge.

Image

### PR DESCRIPTION
**Pull request by MattIPv4**
## Description

Adds an additional condition that the most recent release for a major must be marked as an LTS release before we will show it as LTS on the site, beyond the date check. This ensures that we don't preemptively show a release as LTS when it does not yet have an LTS release, even if we are past the date in the support schedule where it should be LTS.

## Validation

Current release shows.

Before:

```
@node-core/website:dev: 25 Maintenance LTS
@node-core/website:dev: 24 Active LTS
@node-core/website:dev: 23 End-of-life
@node-core/website:dev: 22 Maintenance LTS
@node-core/website:dev: 21 End-of-life
@node-core/website:dev: 20 Maintenance LTS
@node-core/website:dev: 19 End-of-life
@node-core/website:dev: 18 End-of-life
@node-core/website:dev: 17 End-of-life
@node-core/website:dev: 16 End-of-life
@node-core/website:dev: 15 End-of-life
@node-core/website:dev: 14 End-of-life
@node-core/website:dev: 13 End-of-life
@node-core/website:dev: 12 End-of-life
@node-core/website:dev: 11 End-of-life
@node-core/website:dev: 10 End-of-life
@node-core/website:dev: 9 End-of-life
@node-core/website:dev: 8 End-of-life
@node-core/website:dev: 7 End-of-life
@node-core/website:dev: 6 End-of-life
@node-core/website:dev: 5 End-of-life
@node-core/website:dev: 4 End-of-life
@node-core/website:dev: 0 End-of-life
```

After:

```
@node-core/website:dev: 25 Current
@node-core/website:dev: 24 Active LTS
@node-core/website:dev: 23 End-of-life
@node-core/website:dev: 22 Maintenance LTS
@node-core/website:dev: 21 End-of-life
@node-core/website:dev: 20 Maintenance LTS
@node-core/website:dev: 19 End-of-life
@node-core/website:dev: 18 End-of-life
@node-core/website:dev: 17 End-of-life
@node-core/website:dev: 16 End-of-life
@node-core/website:dev: 15 End-of-life
@node-core/website:dev: 14 End-of-life
@node-core/website:dev: 13 End-of-life
@node-core/website:dev: 12 End-of-life
@node-core/website:dev: 11 End-of-life
@node-core/website:dev: 10 End-of-life
@node-core/website:dev: 9 End-of-life
@node-core/website:dev: 8 End-of-life
@node-core/website:dev: 7 End-of-life
@node-core/website:dev: 6 End-of-life
@node-core/website:dev: 5 End-of-life
@node-core/website:dev: 4 End-of-life
@node-core/website:dev: 0 End-of-life
```

## Related Issues

Fixes #8786

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `pnpm format` to ensure the code follows the style guide.
- [ ] I have run `pnpm test` to check if all tests are passing.
- [ ] I have run `pnpm build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by avivkeller — APPROVED** [review]

File: apps/site/next-data/generators/releaseData.mjs [hunk 1]
```diff
@@ -3,18 +3,23 @@
...
   if (endOfLife && now >= new Date(endOfLife)) {
     return 'End-of-life';
   }
 
-  if (maintenanceStart && now >= new Date(maintenanceStart)) {
+  if (
+    latest.lts.isLts &&
+    maintenanceStart &&
+    now >= new Date(maintenanceStart)
+  ) {
```
[the remark this answers is not in the document]
Comment (MattIPv4) [reply apps/site/next-data/generators/releaseData.mjs:18]: This shape is guaranteed: https://github.com/cutenode/nodevu/blob/ebe784ff5fa1293f7be3858a41ec8a42a1db2d37/core/index.js#L145-L149

File: apps/site/next-data/generators/releaseData.mjs [hunk 2]
```diff
@@ -3,18 +3,23 @@
...
 
   if (endOfLife && now >= new Date(endOfLife)) {
     return 'End-of-life';
   }
 
-  if (maintenanceStart && now >= new Date(maintenanceStart)) {
+  if (
+    latest.lts.isLts &&
+    maintenanceStart &&
+    now >= new Date(maintenanceStart)
```
Comment (aduh95) [inline apps/site/next-data/generators/releaseData.mjs:17]: We should only use the date to determine if a release line is EOL. The maintenance status is going away, it's not supposed to be a user-facing information, and `index.json` tells you if a release line is LTS without needing to compare dates with the schedule.

Comment (ovflowd) [reply apps/site/next-data/generators/releaseData.mjs:17]: @MattIPv4 can you please change this to remove the maintenance piece then? Or somehow be able to simplify it?

Comment (MattIPv4) [reply apps/site/next-data/generators/releaseData.mjs:17]: @aduh95 Can you file a separate issue to track that maintenance LTS is going away, and that this needs updating?
