### PR TITLE
fix: handle the potential absence of events

### LINKED ISSUE #7090: Error fetching calendar events
### How to reproduce the issue:

I haven't had a chance to dig in but just saw this in CI (https://github.com/nodejs/nodejs.org/actions/runs/11192012774/job/31115654589?pr=7085)

```
▲ Next.js 14.2.14
  - Experiments (use with caution):
    · largePageDataBytes
    · webpackBuildWorker
    · instrumentationHook

   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping validation of types
   Skipping linting
   Collecting page data ...
   Generating static pages (0/5424) ...
   Generating static pages (1356/5424) 
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:[23](https://github.com/nodejs/nodejs.org/actions/runs/11192012774/job/31115654589?pr=7085#step:11:24)634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}

Error occurred prerendering page "/en/about/get-involved/events". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}

Error occurred prerendering page "/fr/about/get-involved/events". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}

Error occurred prerendering page "/id/about/get-involved/events". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   Generating static pages (2712/54[24](https://github.com/nodejs/nodejs.org/actions/runs/11192012774/job/31115654589?pr=7085#step:11:25)) 
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407[31](https://github.com/nodejs/nodejs.org/actions/runs/11192012774/job/31115654589?pr=7085#step:11:32)6445'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:236[34](https://github.com/nodejs/nodejs.org/actions/runs/11192012774/job/31115654589?pr=7085#step:11:35))
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:2[36](https://github.com/nodejs/nodejs.org/actions/runs/11192012774/job/31115654589?pr=7085#step:11:37)34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}

Error occurred prerendering page "/pt/about/get-involved/events". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '[40](https://github.com/nodejs/nodejs.org/actions/runs/11192012774/job/31115654589?pr=7085#step:11:41)7316445'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}

Error occurred prerendering page "/uk/about/get-involved/events". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   Generating static pages (4068/5[42](https://github.com/nodejs/nodejs.org/actions/runs/11192012774/job/31115654589?pr=7085#step:11:43)4) 
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316[44](https://github.com/nodejs/nodejs.org/actions/runs/11192012774/job/31115654589?pr=7085#step:11:45)5'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '4073164[45](https://github.com/nodejs/nodejs.org/actions/runs/11192012774/job/31115654589?pr=7085#step:11:46)'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}

Error occurred prerendering page "/zh-cn/about/get-involved/events". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}
TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '407316445'
}

Error occurred prerendering page "/zh-tw/about/get-involved/events". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of undefined (reading 'filter')
    at en (/home/runner/work/nodejs.org/nodejs.org/apps/site/.next/server/app/[locale]/[[...path]]/page.js:184:23634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ✓ Generating static pages ([54](https://github.com/nodejs/nodejs.org/actions/runs/11192012774/job/31115654589?pr=7085#step:11:55)24/5424)

> Export encountered errors on following paths:
	/[locale]/[[...path]]/page: /en/about/get-involved/events
	/[locale]/[[...path]]/page: /fr/about/get-involved/events
	/[locale]/[[...path]]/page: /id/about/get-involved/events
	/[locale]/[[...path]]/page: /pt/about/get-involved/events
	/[locale]/[[...path]]/page: /uk/about/get-involved/events
	/[locale]/[[...path]]/page: /zh-cn/about/get-involved/events
	/[locale]/[[...path]]/page: /zh-tw/about/get-involved/events
npm error Lifecycle script `build` failed with error:
npm error code 1
npm error path /home/runner/work/nodejs.org/nodejs.org/apps/site
npm error workspace @node-core/website
npm error location /home/runner/work/nodejs.org/nodejs.org/apps/site
npm error command failed
npm error command sh -c cross-env NODE_NO_WARNINGS=1 next build
npm error Lifecycle script `deploy` failed with error:
npm error code 1
npm error path /home/runner/work/nodejs.org/nodejs.org/apps/site
npm error workspace @node-core/website
npm error location /home/runner/work/nodejs.org/nodejs.org/apps/site
npm error command failed
npm error command sh -c cross-env NEXT_PUBLIC_STATIC_EXPORT=true npm run build
Error:  command finished with error: command (/home/runner/work/nodejs.org/nodejs.org/apps/site) /opt/hostedtoolcache/node/20.17.0/x[64](https://github.com/nodejs/nodejs.org/actions/runs/11192012774/job/31115654589?pr=7085#step:11:65)/bin/npm run deploy exited (1)
Error: @node-core/website#deploy: command (/home/runner/work/nodejs.org/nodejs.org/apps/site) /opt/hostedtoolcache/node/20.17.0/x64/bin/npm run deploy exited (1)
```

### PR DESCRIPTION
**Pull request by mikeesto**
## Description

Resolves https://github.com/nodejs/nodejs.org/issues/7090

## Validation

Open http://localhost:3000/en/about/get-involved/events locally and see no errors. CI for this PR should now also pass.

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]
LGTM

**Review by canerakdas — APPROVED** [review]

File: apps/site/components/MDX/Calendar/UpcomingMeetings.tsx [hunk 1]
```diff
@@ -12,7 +12,7 @@ import styles from './calendar.module.css';
 type GroupedEntries = Record<string, Array<CalendarEvent>>;
 
 const UpcomingMeetings: FC = async () => {
-  const events = await getCalendarEvents(CALENDAR_NODEJS_ID);
+  const events = (await getCalendarEvents(CALENDAR_NODEJS_ID)) ?? [];
```
Comment (ovflowd) [inline apps/site/components/MDX/Calendar/UpcomingMeetings.tsx]: Instead of this, could you update the `getCalendarEvents` function to handle the undefined scenario?

Comment (mikeesto) [reply apps/site/components/MDX/Calendar/UpcomingMeetings.tsx]: Sure, done

**Comment by bmuenzenmeyer** [comment]
sorry @mikeesto I missed this with the introduction of https://github.com/nodejs/nodejs.org/pull/7097 - probably still valid to include
