### PR TITLE
fix: Bitness type in dropdown

### LINKED ISSUE #6613: Pre-built binary download link for Linux X64 is incorrect on official site
### URL:

https://nodejs.org/en/download/prebuilt-binaries

### Browser Name:

Firefox

### Browser Version:

124.0.1

### Operating System:

MacOS Sonoma 14.4.1

### How to reproduce the issue:

1. Navigate to the pre-built binary download page, and select Linux and X64.
2. The download link is `https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-64.tar.xz`, which does not exist; the correct link should be `https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-x64.tar.xz`; there is a missing `x` before 64.
3. I did not verify other download links.

### PR DESCRIPTION
**Pull request by canerakdas**
## Description

When the default bitness information was excluded and non-excluded bitness existed, we were assigning bitness information as a string by default. With this PR, it was possible to assign numbers such as 86 ,64 or strings such as "arm64" or "armv7l" depending on the type of bitness selected.

With this PR, we aim to create the correct link even when the default bitness is disabled from the `getNodeDownloadUrl` method. I will check if we can prepare test cases to check these links 👀 

## Validation

In the preview, download links should be correct

## Related Issues

Fixes #6613

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
Just a quick headsup. On Firefox Bitness information comes as number when it is x64/x86 (as 64 and 86). Whilst on Chrome it comes as a string `x64`, `x86`...

So just, let's please ensure this works both on firefox and chrome 😅

**Comment by canerakdas** [comment]
Thanks for the information @ovflowd , as far as I checked, all the links on the preview match each other in Chrome/Firefox and I checked that they are downloadable. There seems to be no problem, below are the download links in the "Prebuilt Installer", and "Prebuilt Binaries" tabs for both browsers;

<details>
  <summary><h2>Prebuilt Installer</h2></summary>

  ### macOS
  ### x64
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1.pkg
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1.pkg

  ### macOS
  ### ARM64
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1.pkg
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1.pkg

  ---

  ### Windows
  ### x64
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-x64.msi
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-x64.msi

  ### Windows
  ### x86
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-x86.msi
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-x86.msi

  ### Windows
  ### ARM64
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-arm64.msi
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-arm64.msi

</details>

<details>
  <summary><h2>Prebuilt Binaries</h2></summary>

  ### macOS
  ### x64
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-darwin-x64.tar.gz
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-darwin-x64.tar.gz

  ### macOS
  ### ARM64
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-darwin-arm64.tar.gz
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-darwin-arm64.tar.gz

  ---

  ### Windows
  ### x64
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-win-x64.zip
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-win-x64.zip

  ### Windows
  ### x86
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-win-x86.zip
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-win-x86.zip

  ### Windows
  ### ARM64
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-win-arm64.zip
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-win-arm64.zip

  ---

  ### Linux
  ### x64
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-x64.tar.xz
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-x64.tar.xz

  ### Linux
  ### ARMv7
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-armv7l.tar.xz
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-armv7l.tar.xz

  ### Linux
  ### ARM64
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-arm64.tar.xz
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-arm64.tar.xz

  ### Linux
  ### POWER LE
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-ppc64le.tar.xz
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-ppc64le.tar.xz

  ### Linux
  ### System Z
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-s390x.tar.xz
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-s390x.tar.xz

  ---

  ### AIX
  ### Power
  Chrome : https://nodejs.org/dist/v20.12.1/node-v20.12.1-aix-ppc64.tar.gz
  Firefox: https://nodejs.org/dist/v20.12.1/node-v20.12.1-aix-ppc64.tar.gz

</details>

It will take some time to clear my download folder 😂

File: components/Downloads/Release/BitnessDropdown.tsx [hunk 1]
```diff
@@ -64,21 +64,27 @@ const BitnessDropdown: FC = () => {
...
+    const nonExcludedBitness = mappedBitnessValues.find(
+      bitness => !disabledItems.includes(bitness)
     );
 
-    if (currentBittnessExcluded && nonExcludedBitness) {
-      setBitness(nonExcludedBitness);
+    if (currentBitnessExcluded && nonExcludedBitness) {
+      // We set it as a Number for cases where it is 64 or 86 otherwise we are
+      // setting it as a string (ARMv7, ARMv6, etc.)
+      if (Number.isNaN(Number(nonExcludedBitness)) === false) {
```
Comment (ovflowd) [inline components/Downloads/Release/BitnessDropdown.tsx:83]: Could this be transformed into:

```tsx
const numericBitness = Number(nonExcludedBitness);

setBitness(
  numericBitness.toString() === nonExcludedBitness
    ? numericBitness
    : nonExcludedBitness
);
```

I'm not sure if the value actually needs to be a number? If not:

```tsx
const numericBitness = Number(nonExcludedBitness).toString();

setBitness(
  numericBitness === nonExcludedBitness
    ? numericBitness
    : nonExcludedBitness
);
```

**Review by ovflowd — APPROVED** [review]
Awesome stuff! Just left a comment but we can proceed with this :D

**Review by AugustinMauroy — APPROVED** [review]

**Review by aymen94 — APPROVED** [review]

File: components/Downloads/Release/BitnessDropdown.tsx (hunk 1 above)
Comment (ovflowd) [reply components/Downloads/Release/BitnessDropdown.tsx:83]: cc @canerakdas

**Comment by ovflowd** [comment]
FYI @canerakdas is OOO for a few days I'll merge the PR as it is, and then @canerakdas can iterate on my feedback afterwards.

File: components/Downloads/Release/BitnessDropdown.tsx (hunk 1 above)
Comment (Jean681729) [reply components/Downloads/Release/BitnessDropdown.tsx:83]: Approve
