### PR TITLE
fix: fallback to Maintenance LTS if no Active LTS found

### LINKED ISSUE #8248: Download page is blank
### URL:

https://nodejs.org/en/download

### Browser Name:

Chrome

### Browser Version:

141.0.7390.108

### Operating System:

Windows 10, 22H2

### How to reproduce the issue:

1. Open nodejs.org website
2. Navigate to Download page from top menu ( https://nodejs.org/en/download )
3. Actual result: The page contains only header, title and footer, no content
4. Expected result: The page should contain content like on https://nodejs.org/en/download/current page
Tested on both latest Chrome and Firefox, no errors in JS console for some reason.

Image

### PR DESCRIPTION
**Pull request by MattIPv4**
## Description

There is no Active LTS release currently, just Current + Maintenance LTS releases, causing the main download page to render no content as it cannot find an Active LTS release. This updates the logic to allow an array of release statues to be passed in, with the provider trying to find a release with a matching status in the order they're provided in (e.g. it'll pick an Active LTS release even if it is after a Maintenance LTS release).

## Validation

`/en/download` and `/en/download/current` load.

## Related Issues

Resolves #8248

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `pnpm format` to ensure the code follows the style guide.
- [ ] I have run `pnpm test` to check if all tests are passing.
- [ ] I have run `pnpm build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

File: apps/site/components/withDownloadSection.tsx [hunk 1]
```diff
@@ -38,7 +38,7 @@ const WithDownloadSection: FC<WithDownloadSectionProps> = ({
   // Decides which initial release to use based on the current pathname
   const initialRelease = pathname.endsWith('/current')
     ? 'Current'
-    : 'Active LTS';
+    : ['Active LTS' as const, 'Maintenance LTS' as const];
```
[the remark this answers is not in the document]
Comment (MattIPv4) [reply apps/site/components/withDownloadSection.tsx:41]: They're needed.

**Review by flakey5 — APPROVED** [review]

**Review by avivkeller — APPROVED** [review]

**Comment by MattIPv4** [comment]
Requesting fast-track on the basis this is an emergency fix, not sure I even need to request fast-track for that

**Comment by targos** [comment]
"Active" and "Maintenance" LTS stages are important to the Release WG, not really for the public. The website should only care about what is the latest LTS, i.e. the one with the highest version number.

File: apps/site/components/withNodeRelease.tsx [hunk 2]
```diff
@@ -19,12 +19,18 @@ const WithNodeRelease: FC<WithNodeReleaseProps> = async ({
 }) => {
   const releaseData = await provideReleaseData();
 
-  const matchingRelease = releaseData.find(release =>
-    [status].flat().includes(release.status)
-  );
+  let matchingRelease: NodeRelease | undefined;
```
Comment (ovflowd) [inline apps/site/components/withNodeRelease.tsx:22]: nit: could we do a folllo-up PR that doesn't do for and uses proper built-ins to match the repo convention style? cc @nodejs/nodejs-website

File: apps/site/components/withNodeRelease.tsx [hunk 3]
```diff
@@ -19,12 +19,18 @@ const WithNodeRelease: FC<WithNodeReleaseProps> = async ({
 }) => {
   const releaseData = await provideReleaseData();
 
-  const matchingRelease = releaseData.find(release =>
-    [status].flat().includes(release.status)
```
Comment (ovflowd) [inline apps/site/components/withNodeRelease.tsx:23]: The original code would have worked fine, there was no need to refactor this?

**Comment by bmuenzenmeyer** [comment]
> "Active" and "Maintenance" LTS stages are important to the Release WG, not really for the public. The website should only care about what is the latest LTS, i.e. the one with the highest version number.

@targos - agree!

Attendees of Collab Summit talked about this during - https://github.com/openjs-foundation/summit/issues/469 - so hopefully in the nearish future we will introduce more clarity for users and simplicity for the website

File: apps/site/components/withNodeRelease.tsx (hunk 3 above)
Comment (MattIPv4) [reply apps/site/components/withNodeRelease.tsx:23]: No? If there was a Maintenance LTS release in the array before an Active LTS release, the old logic would have picked the Maintenance LTS release. The new logic ensures we've looked at the whole array for an Active LTS release before switching to a Maintenance LTS.

File: apps/site/components/withNodeRelease.tsx (hunk 2 above)
Comment (MattIPv4) [reply apps/site/components/withNodeRelease.tsx:22]: I'm not sure there is a built-in that can do what this is doing? No array methods have a break equivalent?

Comment (ovflowd) [reply apps/site/components/withNodeRelease.tsx:22]: I mean what we were doing before, Using array.find()

File: apps/site/components/withNodeRelease.tsx (hunk 3 above)
Comment (ovflowd) [reply apps/site/components/withNodeRelease.tsx:23]: True, that was an oversight. But I'd still wage over not using for statements within a React component.

File: apps/site/components/withNodeRelease.tsx (hunk 2 above)
Comment (MattIPv4) [reply apps/site/components/withNodeRelease.tsx:22]: No? The old logic was iterating over release data so you can do a find to early return a match from it. The new logic iterates over status but early returns a value from release data, which I don't believe can be done cleanly with array methods?

File: apps/site/components/withNodeRelease.tsx (hunk 3 above)
Comment (MattIPv4) [reply apps/site/components/withNodeRelease.tsx:23]: Given the context of this fix, I'd prefer for robust logic over using newer language syntax, a for loop works perfectly fine and really is doing nothing fundamentally different.
