### PR TITLE
fix: Made RouterSelect inline (#6560)

### LINKED ISSUE #6560: Strange behavior of drop-down menu on download page
### URL:

https://nodejs.org/en/download

### Browser Name:

Chrome

### Browser Version:

123.0.6312.40

### Operating System:

Android 14

### How to reproduce the issue:

1. Go to downloads page
2. Click categories drop-down
3. See the visual bug
Screenshot_20240326-211310

### PR DESCRIPTION
**Pull request by kujo205**
## Description

I changed odd behavior of RouterSelect, now items are under the select
upd:
I also removed translations from labels as labels weren't needed in the design

## Validation
Here how it looks:
image

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by mikeesto — DISMISSED** [review]
Thanks for your PR. Would you be able to rebase it, please? There's a lot of changes in here that aren't related to the Select component.

I think the other issue is that by setting inline to true, we lose the label due to this check here: https://github.com/nodejs/nodejs.org/blob/6f5ad4547cfcfb931e8725afa7da9379129f8bd2/components/Common/Select/index.tsx#L75-L79

File: components/Downloads/Release/VersionDropdown.tsx [hunk 1]
```diff
@@ -21,19 +20,17 @@ const getDropDownStatus = (version: string, status: string) => {
...
     <Select
-      label={t('layouts.download.dropdown.version')}
       values={releases.map(({ status, versionWithPrefix }) => ({
         value: versionWithPrefix,
         label: getDropDownStatus(versionWithPrefix, status),
       }))}
       defaultValue={release.versionWithPrefix}
       onChange={setVersion}
       className="w-40"
-      inline={true}
```
Comment (ovflowd) [inline components/Downloads/Release/VersionDropdown.tsx]: Why removing the ={true)? Usuall it's good to be explicit that this is a boolean.

File: components/Downloads/Release/VersionDropdown.tsx [hunk 2]
```diff
@@ -21,19 +20,17 @@ const getDropDownStatus = (version: string, status: string) => {
 
 const VersionDropdown: FC = () => {
   const { releases, release, setVersion } = useContext(ReleaseContext);
-  const t = useTranslations();
 
   return (
     <Select
-      label={t('layouts.download.dropdown.version')}
```
Comment (ovflowd) [inline components/Downloads/Release/VersionDropdown.tsx:28]: Also an reason for removing the label? Is it because it's inline? Should it also be inline on Mobile? How it interacts on mobile?

Comment (kujo205) [reply components/Downloads/Release/VersionDropdown.tsx:28]: No, there is no label on mobile

Comment (ovflowd) [reply components/Downloads/Release/VersionDropdown.tsx:28]: Right that's on the download page, but what about the other pages that use Router? I assume it's not affected, as the change is only on the RouterSelect?

How does the Select look when open on mobile?

Comment (kujo205) [reply components/Downloads/Release/VersionDropdown.tsx:28]: @ovflowd

No, this won't affect other pages, since this component is only used in 4 other components , 3 of which are located on `download page` and the other usage is in withRouterSelect component, which is HOC for page switcher, check the screenhsot
image

Comment (ovflowd) [reply components/Downloads/Release/VersionDropdown.tsx:28]: I see. Well IMO on mobile screens we shouldn't use Inline Select as it can make navigation harder. Text becomes way smaller. Wdyt?

cc @bmuenzenmeyer

**Review by ovflowd — APPROVED** [review]
Code-wise looks good! Just wondering if on Mobile screens that select won't be too small? But otherwise all good :)

Thank you for this awesome contribution!

**Comment by ovflowd** [comment]
This is good to be merged as it is.

File: components/Downloads/Release/BitnessDropdown.tsx [hunk 3]
```diff
@@ -82,7 +80,6 @@ const BitnessDropdown: FC = () => {
 
   return (
     <Select
-      label={t('layouts.download.dropdown.bitness')}
```
Comment (canerakdas) [inline components/Downloads/Release/BitnessDropdown.tsx:85]: Even if they are not visible in the design, labels are required for accessibility. It would be better to add them again unless there is a different reason

https://dequeuniversity.com/rules/axe/4.8/button-name

Comment (kujo205) [reply components/Downloads/Release/BitnessDropdown.tsx:85]: Good, observation, thanx
I added `ariaLabel` prop to the `Select` component

**Review by canerakdas — APPROVED** [review]
LGTM :shipit: thank you for your contribution

**Review by AugustinMauroy — APPROVED** [review]

**Comment by kujo205** [comment]
@canerakdas hey, how do I pass `UI Review` and `UI Tests` checks? 😙
